# Generated by Django 5.0.6 on 2024-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.TextField()),
                ('to_id', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
