# Generated by Django 5.0.6 on 2024-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='from_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='to_id',
            field=models.IntegerField(),
        ),
    ]
